-- MySQL Script generated by MySQL Workbench
-- 05/24/17 10:21:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yenterprises
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yenterprises
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yenterprises` DEFAULT CHARACTER SET utf8 ;
USE `yenterprises` ;

-- -----------------------------------------------------
-- Table `yenterprises`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`users` (
  `userid` VARCHAR(20) NOT NULL,
  `pwd` VARCHAR(20) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `dateRegistered` DATE NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `id_UNIQUE` (`userid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yenterprises`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creatorID` INT NOT NULL,
  `dateCreated` DATE NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `shortDesc` VARCHAR(50) NOT NULL,
  `longDesc` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_posts_users_idx` (`creatorID` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`creatorID`)
    REFERENCES `yenterprises`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yenterprises`.`modifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`modifications` (
  `postsID` INT NOT NULL,
  `modifierID` INT NOT NULL,
  `dateModified` DATE NOT NULL,
  PRIMARY KEY (`postsID`, `modifierID`),
  INDEX `fk_posts_has_users_users1_idx` (`modifierID` ASC),
  INDEX `fk_posts_has_users_posts1_idx` (`postsID` ASC),
  CONSTRAINT `fk_posts_has_users_posts1`
    FOREIGN KEY (`postsID`)
    REFERENCES `yenterprises`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_users_users1`
    FOREIGN KEY (`modifierID`)
    REFERENCES `yenterprises`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
