-- MySQL Script generated by MySQL Workbench
-- 06/02/17 12:49:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yenterprises
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yenterprises
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yenterprises` DEFAULT CHARACTER SET utf8 ;
USE `yenterprises` ;

-- -----------------------------------------------------
-- Table `yenterprises`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`user` (
  `userId` VARCHAR(20) NOT NULL,
  `pwd` VARCHAR(20) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `dateRegistered` DATE NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `id_UNIQUE` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yenterprises`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `creatorId` VARCHAR(20) NOT NULL,
  `dateCreated` DATE NOT NULL,
  `title` VARCHAR(20) NOT NULL,
  `shortDesc` VARCHAR(50) NOT NULL,
  `longDesc` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`postId`),
  UNIQUE INDEX `id_UNIQUE` (`postId` ASC),
  INDEX `fk_posts_users_idx` (`creatorId` ASC),
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`creatorId`)
    REFERENCES `yenterprises`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yenterprises`.`modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yenterprises`.`modification` (
  `postId` INT NOT NULL,
  `modifierId` VARCHAR(20) NOT NULL,
  `dateModified` DATE NOT NULL,
  PRIMARY KEY (`postId`, `modifierId`),
  INDEX `fk_posts_has_users_users1_idx` (`modifierId` ASC),
  INDEX `fk_posts_has_users_posts1_idx` (`postId` ASC),
  CONSTRAINT `fk_posts_has_users_posts1`
    FOREIGN KEY (`postId`)
    REFERENCES `yenterprises`.`post` (`postId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_has_users_users1`
    FOREIGN KEY (`modifierId`)
    REFERENCES `yenterprises`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
